version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - SERVICES=serverless
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  cdk:
    image: awscdk:latest
    build:
      context: ./
      dockerfile: Dockerfile-cdk
    command: "cdklocal bootstrap"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
    volumes:
      - ./cdk/:/opt/stack
      - ./lambda:/code/lambda

  sam-api:
    image: samcli:latest
    command: local start-api -d 5858 --host 0.0.0.0 --warm-containers EAGER
    build:
      context: ./
      dockerfile: Dockerfile-sam
    ports:
      - 3000:3000
    environment:
      - VOLUME_DIR=${ROOT}
      - DOCKER_HOST=unix:///var/run/docker.sock
    working_dir: ${ROOT}
    volumes:
      - ${ROOT}:${ROOT}
      - "/var/run/docker.sock:/var/run/docker.sock"